name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        ffmpeg-version: ['4.4.2', '5.1.2', '6.1.1', '7.0.1']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
          # TODO: This is installing ffmpeg with 6 GPL stuff enabled. That's just
          # for testing for now so it's OK. But before we release we should make
          # sure it's not using GPL stuff by e.g. building from source like
          # in torchaudio.
          # TODO: Make this work with ffmpeg 4 to 7 inclusive.
          conda install "ffmpeg=${{ matrix.ffmpeg-version }}" pkg-config -c conda-forge
          ffmpeg -version
      - name: Build and install torchcodec
        run: |
          python -m pip install -e ".[dev]" --no-build-isolation -vvv
      - name: Smoke test
        run: |
          python test/decoders/manual_smoke_test.py
          # TODO: diff the output frame with its expeceted value
      - name: Run tests
        run: |
          pytest test
