name: Build wheel

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.12']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install Pytorch
        run: |
          python -m pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Build the torchcodec wheel
        run: |
          .github/scripts/assert_ffmpeg_not_installed.sh

          python -m pip install build
          BUILD_AGAINST_ALL_FFMPEG_FROM_S3=1 python -m build . --wheel -vvv --no-isolation
      - uses: actions/upload-artifact@v4
        with:
          name: sdist-linux_x86_${{ matrix.python-version }}
          path: dist/*

  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.12']
        ffmpeg-version-for-tests: ['4.4.2', '5.1.2', '6.1.1', '7.0.1']
    if: ${{ always() }}
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist-linux_x86_${{ matrix.python-version }}
          path: dist/
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install PyTorch
        run: |
          python -m pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Install torchcodec from the wheel
        run: |
          wheel_path=`find dist -type f`
          echo Installing $wheel_path
          python -m pip install $wheel_path

      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install ffmpeg, post build
        run: |
          # Ideally we would have checked for that before installing the wheel,
          # but we need to checkout the repo to access this file, and we don't
          # want to checkout the repo before installing the wheel to avoid any
          # side-effect. It's OK.
          .github/scripts/assert_ffmpeg_not_installed.sh

          conda install "ffmpeg=${{ matrix.ffmpeg-version-for-tests }}" -c conda-forge
          ffmpeg -version

      - name: Install test dependencies
        run: |
          python -m pip install --pre torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
          # TODO: Find a way to get those dependencies from pyproject.toml
          python -m pip install numpy pytest pillow opencv-python
      
      - name: Delete src folder
        run: |
          # The only reason we checked-out the repo is to get access to the
          # tests. We don't care about the rest. Out of precaution, we delete
          # the src/ folder to be extra sure that we're running the code from
          # the installed wheel rather than from the source.
          # Note that in theory, running the code from the sources should a)
          # never happen and b) fail loudly because the built .so files aren't
          # present there.
          rm -r src/
          ls
      - name: Smoke test
        run: |
          python test/decoders/manual_smoke_test.py
          # TODO: diff the output frame with its expeceted value
      - name: Run Python tests
        run: |
          pytest test
